package com.example.ui.localization

object LocalStrings {
    private val sq = mapOf(
        "app_tagline" to "Mësoni matematikën përmes aventurave të animuara!",
        "select_avatar" to "Zgjidh Avatarin:",
        "enter_name" to "Emri i Fëmijës",
        "enter_name_hint" to "p.sh. Lorik, Hana...",
        "enter_age" to "Mosha e Fëmijës",
        "difficulty" to "Vështirësia e Lojës:",
        "diff_easy" to "E Lehtë (Mbledhje/Zbritje 1-10)",
        "diff_medium" to "E Mesme (Mbledhje/Zbritje 1-50, Shumëzim)",
        "diff_hard" to "E Vështirë (Pjesëtim, Shifra deri 100)",
        "language" to "Zgjidh Gjuhën:",
        "btn_create_profile" to "Krijo Profilin 🚀",
        "btn_add_child" to "Shto një Fëmijë +",
        "no_profiles" to "Mirësevjen! Nuk ka ende profile fëmijësh. Krijo një profil që të fillojmë aventurën! 🎉",
        "welcome" to "Përshëndetje,",
        "play_adventure" to "Fillo Aventurën 🏝️",
        "my_stickers" to "Dhomëza e Lodrave 🧸",
        "parents_hub" to "Këndi i Prindërve ⚙️",
        "coins" to "Monedha",
        "badges" to "Shpërblime",
        "change_profile" to "Ndrysho Profil",
        "quest_addition" to "Pylli i Mbushur (Mbledhje)",
        "quest_subtraction" to "Lumi i Kthelltë (Zbritje)",
        "quest_multiplication" to "Mali i Akullt (Shumëzim)",
        "quest_division" to "Kështjella Kozmike (Pjesëtim)",
        "quest_addition_desc" to "Ndihmo lepurushin e etur duke mbledhur manaferra dhe mollë magjike në pyll!",
        "quest_subtraction_desc" to "Ndihmo peshkun e humbur të shpëtojë nga shpella duke zbritur flluskat!",
        "quest_multiplication_desc" to "Ndihmo arushin polar të bashkojë blloqet e akullit të shumëzuara për iglunë e tij!",
        "quest_division_desc" to "Ndihmo alienin të ndajë fishekzjarret dhe yjet në sasi të barabarta për raketën!",
        "btn_solve" to "Zgjidhe",
        "quit_adventure" to "Anulo Aventurën 🚪",
        "question_counter" to "Sfida",
        "congrats" to "Uraaa! 🎉 Aventurë e Suksesshme!",
        "earned_coins" to "Ti fitove",
        "earned_badge" to "Sapo fitove një Badge të Re Meritash! 🏆",
        "back_home" to "Kthehu në Sallon 🏠",
        "correct_answer" to "Bravo! Përgjigje e Saktë! ⭐️ (+10 Monedha)",
        "wrong_answer" to "Afër, por jo plotësisht! Provo sërish, ti mundesh! ❤️",
        "sticker_shop" to "Koleksioni i Lodrave",
        "sticker_shop_desc" to "Shpenzo monedhat e arta që fitove gjatë lojës duke blerë ngjitëse të mrekullueshme!",
        "buy_for" to "Bli për",
        "unlocked" to "E zhbllokuar Shkëlqyeshëm!",
        "insufficient_coins" to "Nuk ke monedha të mjaftueshme! Luaj më shumë aventura për të fituar monedha! 🪙",
        "parents_gate_title" to "🔒 KONTROLLI PËR PRINDËR",
        "parents_gate_desc" to "Kjo zonë është vetëm për prindërit e fëmijës. Ju lutem vërtetoni duke zgjidhur këtë ekuacion të rriturish:",
        "parents_gate_error" to "Oh! Kjo nuk është e saktë. Kërko ndihmën e prindit tënd! 😊",
        "btn_submit" to "Vërteto",
        "parent_title" to "Këndi i Prindërve",
        "parent_subtitle" to "Raporti offline i vështirësisë dhe performancës matematike",
        "accuracy" to "Saktësia Matematike",
        "quests_completed" to "Aventura të zgjidhura",
        "history_logs" to "Historiku i Detajuar i Ushtrimeve",
        "delete_profile_warn" to "KUJDES: Kjo fshin plotësisht profilin e fëmijës dhe historikun e tij prapëseprapë. A dëshiron të vazhdosh?",
        "btn_delete" to "Fshij Profilin 🚮",
        "no_logs" to "Asnjë ushtrim i plotësuar ende. Filloni të luani që të gjenerohen grafikët e parë!",
        "avatar_bunny" to "Lepurushi Llapaqesh",
        "avatar_fox" to "Dhelpra Bisht-Kërcore",
        "avatar_bear" to "Arushi Polar",
        "avatar_lion" to "Luani Flokë-Mëndafsh",
        "avatar_owl" to "Bufi i Ditur",
        "avatar_panda" to "Panda Ngathtarake",
        "lbl_active_profile" to "Fëmija Aktiv:",
        "lbl_difficulty" to "Niveli aktual:",
        "lbl_language" to "Gjuha:",
        "lbl_accuracy_val" to "Saktësia:",
        "lbl_solved" to "Gjithsej pyetje:",
        "lbl_timestamp" to "Koha:",
        "lbl_rewards_tab" to "Zhbllokimet e Mia",
        "lbl_shop_tab" to "Dyqani i Ngjitëseve",
        "lbl_toys_box" to "Arka e Lodrave të Blerë"
    )

    private val en = mapOf(
        "app_tagline" to "Learn math through interactive cartoon adventures!",
        "select_avatar" to "Choose Your Avatar:",
        "enter_name" to "Child's Name",
        "enter_name_hint" to "e.g. Liam, Emma...",
        "enter_age" to "Child's Age",
        "difficulty" to "Game Difficulty:",
        "diff_easy" to "Easy (Addition/Subtraction 1-10)",
        "diff_medium" to "Medium (Addition/Subtraction 1-50, Mult)",
        "diff_hard" to "Hard (Division, Numbers up to 100)",
        "language" to "Choose Language:",
        "btn_create_profile" to "Create Profile 🚀",
        "btn_add_child" to "Add a Child +",
        "no_profiles" to "Welcome! There are no children profiles yet. Create a profile to start the adventure! 🎉",
        "welcome" to "Hello,",
        "play_adventure" to "Start Adventure 🏝️",
        "my_stickers" to "Toy Chest 🧸",
        "parents_hub" to "Parents Corner ⚙️",
        "coins" to "Coins",
        "badges" to "Badges",
        "change_profile" to "Switch Profile",
        "quest_addition" to "Magic Forest (Addition)",
        "quest_subtraction" to "Deep River (Subtraction)",
        "quest_multiplication" to "Ice Mountain (Multiplication)",
        "quest_division" to "Space Castle (Division)",
        "quest_addition_desc" to "Help the thirsty bunny gather glowing berries and apples in the magic woods!",
        "quest_subtraction_desc" to "Help the lost fish escape the underwater cave by popping subtraction bubbles!",
        "quest_multiplication_desc" to "Help the polar bear carry stacked ice blocks for his cozy igloo by multiplying crystals!",
        "quest_division_desc" to "Help the friendly alien split rocket crackers and stars equally to launch his ship!",
        "btn_solve" to "Solve",
        "quit_adventure" to "Exit Adventure 🚪",
        "question_counter" to "Challenge",
        "congrats" to "Hooray! 🎉 Adventure Accomplished!",
        "earned_coins" to "You earned",
        "earned_badge" to "You unlocked a new Performance Badge! 🏆",
        "back_home" to "Back to Playroom 🏠",
        "correct_answer" to "Awesome! Correct Answer! ⭐️ (+10 Coins)",
        "wrong_answer" to "Close, but not quite! Try again, you can do it! ❤️",
        "sticker_shop" to "Sticker & Toy Chest",
        "sticker_shop_desc" to "Spend your gold coins earned in adventures to buy awesome animated toys and stickers!",
        "buy_for" to "Buy for",
        "unlocked" to "Successfully Unlocked!",
        "insufficient_coins" to "Not enough coins! Play more adventures to earn sparkling gold coins! 🪙",
        "parents_gate_title" to "🔒 PARENTS LOCK",
        "parents_gate_desc" to "This section is restricted to parents. Please verify you are a parent by solving this equation:",
        "parents_gate_error" to "Oops! That's not correct. Ask your parent for help! 😊",
        "btn_submit" to "Verify",
        "parent_title" to "Parents Control",
        "parent_subtitle" to "Offline progress reporting & math performance tracking",
        "accuracy" to "Math Accuracy",
        "quests_completed" to "Quests Completed",
        "history_logs" to "Detailed Exercise Log History",
        "delete_profile_warn" to "WARNING: This will permanently delete the child's profile and entire progress log. Understood?",
        "btn_delete" to "Delete Profile 🚮",
        "no_logs" to "No completed exercises yet. Start playing mathematical quests to generate your first charts!",
        "avatar_bunny" to "Happy Bunny",
        "avatar_fox" to "Wiggle Fox",
        "avatar_bear" to "Polar Buddy",
        "avatar_lion" to "Golden Lion",
        "avatar_owl" to "Wise Owl",
        "avatar_panda" to "Chubby Panda",
        "lbl_active_profile" to "Active Child:",
        "lbl_difficulty" to "Current level:",
        "lbl_language" to "Language:",
        "lbl_accuracy_val" to "Accuracy:",
        "lbl_solved" to "Total Solved:",
        "lbl_timestamp" to "Date Time:",
        "lbl_rewards_tab" to "My Badges",
        "lbl_shop_tab" to "Toy Store",
        "lbl_toys_box" to "Owned Kids Chest"
    )

    fun get(key: String, lang: String): String {
        return if (lang.lowercase() == "sq") {
            sq[key] ?: en[key] ?: key
        } else {
            en[key] ?: key
        }
    }
}
