package com.example.ui.localization

object LocalStrings {
    private val sq = mapOf(
        "app_tagline" to "Mësoni matematikën përmes aventurave të animuara!",
        "select_avatar" to "Zgjidh Avatarin:",
        "enter_name" to "Emri i Fëmijës",
        "enter_name_hint" to "p.sh. Lorik, Hana...",
        "enter_age" to "Mosha e Fëmijës",
        "difficulty" to "Vështirësia e Lojës:",
        "diff_easy" to "E Lehtë (Mbledhje/Zbritje 1-10)",
        "diff_medium" to "E Mesme (Mbledhje/Zbritje 1-50, Shumëzim)",
        "diff_hard" to "E Vështirë (Pjesëtim, Shifra deri 100)",
        "language" to "Zgjidh Gjuhën:",
        "btn_create_profile" to "Krijo Profilin 🚀",
        "btn_add_child" to "Shto një Fëmijë +",
        "no_profiles" to "Mirësevjen! Nuk ka ende profile fëmijësh. Krijo një profil që të fillojmë aventurën! 🎉",
        "welcome" to "Përshëndetje,",
        "play_adventure" to "Fillo Aventurën 🏝️",
        "my_stickers" to "Dhomëza e Lodrave 🧸",
        "parents_hub" to "Këndi i Prindërve ⚙️",
        "coins" to "Monedha",
        "badges" to "Shpërblime",
        "change_profile" to "Ndrysho Profil",
        "quest_addition" to "Pylli i Mbushur (Mbledhje)",
        "quest_subtraction" to "Lumi i Kthelltë (Zbritje)",
        "quest_multiplication" to "Mali i Akullt (Shumëzim)",
        "quest_division" to "Kështjella Kozmike (Pjesëtim)",
        "quest_addition_desc" to "Ndihmo lepurushin e etur duke mbledhur manaferra dhe mollë magjike në pyll!",
        "quest_subtraction_desc" to "Ndihmo peshkun e humbur të shpëtojë nga shpella duke zbritur flluskat!",
        "quest_multiplication_desc" to "Ndihmo arushin polar të bashkojë blloqet e akullit të shumëzuara për iglunë e tij!",
        "quest_division_desc" to "Ndihmo alienin të ndajë fishekzjarret dhe yjet në sasi të barabarta për raketën!",
        "btn_solve" to "Zgjidhe",
        "quit_adventure" to "Anulo Aventurën 🚪",
        "question_counter" to "Sfida",
        "congrats" to "Uraaa! 🎉 Aventurë e Suksesshme!",
        "earned_coins" to "Ti fitove",
        "earned_badge" to "Sapo fitove një Badge të Re Meritash! 🏆",
        "back_home" to "Kthehu në Sallon 🏠",
        "correct_answer" to "Bravo! Përgjigje e Saktë! ⭐️ (+10 Monedha)",
        "wrong_answer" to "Afër, por jo plotësisht! Provo sërish, ti mundesh! ❤️",
        "sticker_shop" to "Koleksioni i Lodrave",
        "sticker_shop_desc" to "Shpenzo monedhat e arta që fitove gjatë lojës duke blerë ngjitëse të mrekullueshme!",
        "buy_for" to "Bli për",
        "unlocked" to "E zhbllokuar Shkëlqyeshëm!",
        "insufficient_coins" to "Nuk ke monedha të mjaftueshme! Luaj më shumë aventura për të fituar monedha! 🪙",
        "parents_gate_title" to "🔒 KONTROLLI PËR PRINDËR",
        "parents_gate_desc" to "Kjo zonë është vetëm për prindërit e fëmijës. Ju lutem vërtetoni duke zgjidhur këtë ekuacion të rriturish:",
        "parents_gate_error" to "Oh! Kjo nuk është e saktë. Kërko ndihmën e prindit tënd! 😊",
        "btn_submit" to "Vërteto",
        "parent_title" to "Këndi i Prindërve",
        "parent_subtitle" to "Raporti offline i vështirësisë dhe performancës matematike",
        "accuracy" to "Saktësia Matematike",
        "quests_completed" to "Aventura të zgjidhura",
        "history_logs" to "Historiku i Detajuar i Ushtrimeve",
        "delete_profile_warn" to "KUJDES: Kjo fshin plotësisht profilin e fëmijës dhe historikun e tij prapëseprapë. A dëshiron të vazhdosh?",
        "btn_delete" to "Fshij Profilin 🚮",
        "no_logs" to "Asnjë ushtrim i plotësuar ende. Filloni të luani që të gjenerohen grafikët e parë!",
        "avatar_bunny" to "Lepurushi Llapaqesh",
        "avatar_fox" to "Dhelpra Bisht-Kërcore",
        "avatar_bear" to "Arushi Polar",
        "avatar_lion" to "Luani Flokë-Mëndafsh",
        "avatar_owl" to "Bufi i Ditur",
        "avatar_panda" to "Panda Ngathtarake",
        "lbl_active_profile" to "Fëmija Aktiv:",
        "lbl_difficulty" to "Niveli aktual:",
        "lbl_language" to "Gjuha:",
        "lbl_accuracy_val" to "Saktësia:",
        "lbl_solved" to "Gjithsej pyetje:",
        "lbl_timestamp" to "Koha:",
        "lbl_rewards_tab" to "Zhbllokimet e Mia",
        "lbl_shop_tab" to "Dyqani i Ngjitëseve",
        "lbl_toys_box" to "Arka e Lodrave të Blerë",
        "range_selector_title" to "Gama e Numrave për Mbledhje/Zbritje:",
        "range_1_10" to "Prej 1 deri në 10 🧸",
        "range_10_100" to "Prej 10 deri në 100 🚀",
        "quest_tracing" to "Mësimi i Shkronjave ✍️",
        "quest_tracing_desc" to "Ndihmo në formimin e shkronjave me vija të ndërprera duke ndjekur shigjetën për të mësuar shkrimin!",
        "tracing_title" to "Mësimi i Shkronjave",
        "btn_clear" to "Fshij Vizatimin",
        "btn_undo" to "Kthehu Mbrapsht",
        "btn_back" to "Salloni 🏠",
        "congrats_tracing" to "Uraaa! 🎉 Shkronja u krye! Mbushur me sukses! (+10 Monedha)",
        "btn_next" to "Tjetra ➡️",
        "hint_start_arrow" to "Fillo këtu 👇"
    )

    private val en = mapOf(
        "app_tagline" to "Learn math through interactive cartoon adventures!",
        "select_avatar" to "Choose Your Avatar:",
        "enter_name" to "Child's Name",
        "enter_name_hint" to "e.g. Liam, Emma...",
        "enter_age" to "Child's Age",
        "difficulty" to "Game Difficulty:",
        "diff_easy" to "Easy (Addition/Subtraction 1-10)",
        "diff_medium" to "Medium (Addition/Subtraction 1-50, Mult)",
        "diff_hard" to "Hard (Division, Numbers up to 100)",
        "language" to "Choose Language:",
        "btn_create_profile" to "Create Profile 🚀",
        "btn_add_child" to "Add a Child +",
        "no_profiles" to "Welcome! There are no children profiles yet. Create a profile to start the adventure! 🎉",
        "welcome" to "Hello,",
        "play_adventure" to "Start Adventure 🏝️",
        "my_stickers" to "Toy Chest 🧸",
        "parents_hub" to "Parents Corner ⚙️",
        "coins" to "Coins",
        "badges" to "Badges",
        "change_profile" to "Switch Profile",
        "quest_addition" to "Magic Forest (Addition)",
        "quest_subtraction" to "Deep River (Subtraction)",
        "quest_multiplication" to "Ice Mountain (Multiplication)",
        "quest_division" to "Space Castle (Division)",
        "quest_addition_desc" to "Help the thirsty bunny gather glowing berries and apples in the magic woods!",
        "quest_subtraction_desc" to "Help the lost fish escape the underwater cave by popping subtraction bubbles!",
        "quest_multiplication_desc" to "Help the polar bear carry stacked ice blocks for his cozy igloo by multiplying crystals!",
        "quest_division_desc" to "Help the friendly alien split rocket crackers and stars equally to launch his ship!",
        "btn_solve" to "Solve",
        "quit_adventure" to "Exit Adventure 🚪",
        "question_counter" to "Challenge",
        "congrats" to "Hooray! 🎉 Adventure Accomplished!",
        "earned_coins" to "You earned",
        "earned_badge" to "You unlocked a new Performance Badge! 🏆",
        "back_home" to "Back to Playroom 🏠",
        "correct_answer" to "Awesome! Correct Answer! ⭐️ (+10 Coins)",
        "wrong_answer" to "Close, but not quite! Try again, you can do it! ❤️",
        "sticker_shop" to "Sticker & Toy Chest",
        "sticker_shop_desc" to "Spend your gold coins earned in adventures to buy awesome animated toys and stickers!",
        "buy_for" to "Buy for",
        "unlocked" to "Successfully Unlocked!",
        "insufficient_coins" to "Not enough coins! Play more adventures to earn sparkling gold coins! 🪙",
        "parents_gate_title" to "🔒 PARENTS LOCK",
        "parents_gate_desc" to "This section is restricted to parents. Please verify you are a parent by solving this equation:",
        "parents_gate_error" to "Oops! That's not correct. Ask your parent for help! 😊",
        "btn_submit" to "Verify",
        "parent_title" to "Parents Control",
        "parent_subtitle" to "Offline progress reporting & math performance tracking",
        "accuracy" to "Math Accuracy",
        "quests_completed" to "Quests Completed",
        "history_logs" to "Detailed Exercise Log History",
        "delete_profile_warn" to "WARNING: This will permanently delete the child's profile and entire progress log. Understood?",
        "btn_delete" to "Delete Profile 🚮",
        "no_logs" to "No completed exercises yet. Start playing mathematical quests to generate your first charts!",
        "avatar_bunny" to "Happy Bunny",
        "avatar_fox" to "Wiggle Fox",
        "avatar_bear" to "Polar Buddy",
        "avatar_lion" to "Golden Lion",
        "avatar_owl" to "Wise Owl",
        "avatar_panda" to "Chubby Panda",
        "lbl_active_profile" to "Active Child:",
        "lbl_difficulty" to "Current level:",
        "lbl_language" to "Language:",
        "lbl_accuracy_val" to "Accuracy:",
        "lbl_solved" to "Total Solved:",
        "lbl_timestamp" to "Date Time:",
        "lbl_rewards_tab" to "My Badges",
        "lbl_shop_tab" to "Toy Store",
        "lbl_toys_box" to "Owned Kids Chest",
        "range_selector_title" to "Add/Sub Learning Number Range:",
        "range_1_10" to "Learn 1 to 10 🧸",
        "range_10_100" to "Learn 10 to 100 🚀",
        "quest_tracing" to "Learn Letters Tracing ✍️",
        "quest_tracing_desc" to "Help trace over letters using dashed lines and guide arrows to practice writing!",
        "tracing_title" to "Letter Tracing Table",
        "btn_clear" to "Clear Painting",
        "btn_undo" to "Undo Line",
        "btn_back" to "Playroom 🏠",
        "congrats_tracing" to "Hooray! 🎉 Letter finished successfully! (+10 Coins)",
        "btn_next" to "Next Letter ➡️",
        "hint_start_arrow" to "Start here 👇"
    )

    val de = mapOf(
        "app_tagline" to "Lerne Mathe durch interaktive Abenteuer!",
        "select_avatar" to "Wähle deinen Avatar:",
        "enter_name" to "Name des Kindes",
        "enter_name_hint" to "z.B. Lukas, Anna...",
        "enter_age" to "Alter des Kindes",
        "difficulty" to "Schwierigkeitsgrad:",
        "diff_easy" to "Einfach (Plus/Minus 1-10)",
        "diff_medium" to "Mittel (Plus/Minus 1-50, Mal)",
        "diff_hard" to "Schwer (Geteilt, Zahlen bis 100)",
        "language" to "Sprache wählen:",
        "btn_create_profile" to "Profil erstellen 🚀",
        "btn_add_child" to "Kind hinzufügen +",
        "no_profiles" to "Willkommen! Es gibt noch keine Profile. Erstelle eins, um zu starten! 🎉",
        "welcome" to "Hallo,",
        "play_adventure" to "Abenteuer starten 🏝️",
        "my_stickers" to "Spielzeugkiste 🧸",
        "parents_hub" to "Elternecke ⚙️",
        "coins" to "Münzen",
        "badges" to "Abzeichen",
        "change_profile" to "Profil wechseln",
        "quest_addition" to "Zauberwald (Plus)",
        "quest_subtraction" to "Tiefer Fluss (Minus)",
        "quest_multiplication" to "Eisberg (Mal)",
        "quest_division" to "Weltraumschloss (Geteilt)",
        "quest_addition_desc" to "Hilf dem durstigen Häschen, Beeren im Wald zu sammeln!",
        "quest_subtraction_desc" to "Hilf dem Fisch in der Höhle, indem du Blasen abziehst!",
        "quest_multiplication_desc" to "Hilf dem Eisbären, Eisblöcke für sein Iglu zu multiplizieren!",
        "quest_division_desc" to "Hilf dem Alien, Sterne für seine Rakete aufzuteilen!",
        "btn_solve" to "Lösen",
        "quit_adventure" to "Abenteuer beenden 🚪",
        "question_counter" to "Herausforderung",
        "congrats" to "Hurra! 🎉 Abenteuer geschafft!",
        "earned_coins" to "Du hast verdient",
        "earned_badge" to "Du hast ein neues Abzeichen! 🏆",
        "back_home" to "Zurück 🏠",
        "correct_answer" to "Klasse! Richtige Antwort! ⭐️ (+10 Münzen)",
        "wrong_answer" to "Knapp daneben! Versuch es nochmal! ❤️",
        "sticker_shop" to "Sticker- & Spielzeugkiste",
        "sticker_shop_desc" to "Gib deine gesammelten Münzen für tolle Sticker aus!",
        "buy_for" to "Kaufen für",
        "unlocked" to "Erfolgreich freigeschaltet!",
        "insufficient_coins" to "Nicht genug Münzen! Spiele mehr Abenteuer! 🪙",
        "parents_gate_title" to "🔒 ELTERNSICHERUNG",
        "parents_gate_desc" to "Nur für Eltern. Bitte löse diese Aufgabe:",
        "parents_gate_error" to "Ups! Das ist nicht richtig. Frag deine Eltern! 😊",
        "btn_submit" to "Bestätigen",
        "parent_title" to "Elternkontrolle",
        "parent_subtitle" to "Offline-Berichte & Mathe-Ergebnisse",
        "accuracy" to "Mathe-Genauigkeit",
        "quests_completed" to "Abgeschlossene Aufgaben",
        "history_logs" to "Detaillierter Übungsverlauf",
        "delete_profile_warn" to "WARNUNG: Dies wird das Profil und den gesamten Fortschritt löschen.",
        "btn_delete" to "Profil löschen 🚮",
        "no_logs" to "Noch keine Übungen. Beginne zu spielen!",
        "avatar_bunny" to "Häschen",
        "avatar_fox" to "Fuchs",
        "avatar_bear" to "Eisbär",
        "avatar_lion" to "Löwe",
        "avatar_owl" to "Eule",
        "avatar_panda" to "Panda",
        "lbl_active_profile" to "Aktives Kind:",
        "lbl_difficulty" to "Level:",
        "lbl_language" to "Sprache:",
        "lbl_accuracy_val" to "Genauigkeit:",
        "lbl_solved" to "Gelöst:",
        "lbl_timestamp" to "Datum:",
        "lbl_rewards_tab" to "Meine Abzeichen",
        "lbl_shop_tab" to "Spielladen",
        "lbl_toys_box" to "Gekaufte Spielzeuge",
        "range_selector_title" to "Zahlenbereich:",
        "range_1_10" to "Lerne 1 bis 10 🧸",
        "range_10_100" to "Lerne 10 bis 100 🚀",
        "quest_tracing" to "Nachspuren ✍️",
        "quest_tracing_desc" to "Hilf, Buchstaben nachzuzeichnen!",
        "tracing_title" to "Buchstaben Nachspuren",
        "btn_clear" to "Löschen",
        "btn_undo" to "Rückgängig",
        "btn_back" to "Zurück 🏠",
        "congrats_tracing" to "Hurra! 🎉 Buchstabe erfolgreich beendet! (+10 Münzen)",
        "btn_next" to "Nächster ➡️",
        "hint_start_arrow" to "Starten 👇"
    )

    val it = mapOf(
        "app_tagline" to "Impara la matematica con avventure interattive!",
        "select_avatar" to "Scegli il tuo Avatar:",
        "enter_name" to "Nome del Bambino",
        "enter_name_hint" to "es. Luca, Giulia...",
        "enter_age" to "Età del Bambino",
        "difficulty" to "Difficoltà del Gioco:",
        "diff_easy" to "Facile (Addizioni/Sottrazioni 1-10)",
        "diff_medium" to "Medio (Add/Sot 1-50, Moltiplicazioni)",
        "diff_hard" to "Difficile (Divisioni, Numeri fino a 100)",
        "language" to "Seleziona Lingua:",
        "btn_create_profile" to "Crea Profilo 🚀",
        "btn_add_child" to "Aggiungi Bambino +",
        "no_profiles" to "Benvenuto! Creane uno per iniziare l'avventura! 🎉",
        "welcome" to "Ciao,",
        "play_adventure" to "Inizia L'Avventura 🏝️",
        "my_stickers" to "Giocattoli 🧸",
        "parents_hub" to "Area Genitori ⚙️",
        "coins" to "Monete",
        "badges" to "Distintivi",
        "change_profile" to "Cambia Profilo",
        "quest_addition" to "Foresta (Addizioni)",
        "quest_subtraction" to "Fiume (Sottrazioni)",
        "quest_multiplication" to "Ghiaccio (Moltiplicazioni)",
        "quest_division" to "Spazio (Divisioni)",
        "quest_addition_desc" to "Raccogli bacche magiche nel bosco!",
        "quest_subtraction_desc" to "Aiuta il pesciolino facendo scoppiare le bolle!",
        "quest_multiplication_desc" to "Moltiplica i blocchi di ghiaccio!",
        "quest_division_desc" to "Dividi le stelle per il razzo!",
        "btn_solve" to "Risolvi",
        "quit_adventure" to "Esci 🚪",
        "question_counter" to "Sfida",
        "congrats" to "Evviva! 🎉 Avventura Completata!",
        "earned_coins" to "Hai guadagnato",
        "earned_badge" to "Hai sbloccato un Distintivo! 🏆",
        "back_home" to "Torna alla Stanza 🏠",
        "correct_answer" to "Bravissimo! Esatta! ⭐️ (+10 Monete)",
        "wrong_answer" to "Quasi! Riprova, ce la puoi fare! ❤️",
        "sticker_shop" to "Giocattoli",
        "sticker_shop_desc" to "Spendi le monete per fantastici giocattoli!",
        "buy_for" to "Compra per",
        "unlocked" to "Sbloccato!",
        "insufficient_coins" to "Non hai abbastanza monete! Gioca di più! 🪙",
        "parents_gate_title" to "🔒 BLOCCO GENITORI",
        "parents_gate_desc" to "Risolvi questa equazione:",
        "parents_gate_error" to "Ups! Chiedi aiuto a un genitore! 😊",
        "btn_submit" to "Verifica",
        "parent_title" to "Controllo Genitori",
        "parent_subtitle" to "Resoconto dei progressi",
        "accuracy" to "Precisione",
        "quests_completed" to "Missioni Completate",
        "history_logs" to "Cronologia Esercizi",
        "delete_profile_warn" to "ATTENZIONE: Questo eliminerà il profilo. Procedere?",
        "btn_delete" to "Elimina Profilo 🚮",
        "no_logs" to "Nessun esercizio completato.",
        "avatar_bunny" to "Coniglietto",
        "avatar_fox" to "Volpe",
        "avatar_bear" to "Orso",
        "avatar_lion" to "Leone",
        "avatar_owl" to "Gufo",
        "avatar_panda" to "Panda",
        "lbl_active_profile" to "Bambino Attivo:",
        "lbl_difficulty" to "Livello:",
        "lbl_language" to "Lingua:",
        "lbl_accuracy_val" to "Precisione:",
        "lbl_solved" to "Risolti in Totale:",
        "lbl_timestamp" to "Data:",
        "lbl_rewards_tab" to "Distintivi",
        "lbl_shop_tab" to "Negozio",
        "lbl_toys_box" to "I Miei Giocattoli",
        "range_selector_title" to "Numeri:",
        "range_1_10" to "Impara 1 a 10 🧸",
        "range_10_100" to "Impara 10 a 100 🚀",
        "quest_tracing" to "Ricalca ✍️",
        "quest_tracing_desc" to "Traccia le lettere lungo le linee!",
        "tracing_title" to "Ricalcare Lettere",
        "btn_clear" to "Cancella",
        "btn_undo" to "Annulla",
        "btn_back" to "Stanza 🏠",
        "congrats_tracing" to "Urrà! 🎉 Lettera terminata! (+10 Monete)",
        "btn_next" to "Prossima ➡️",
        "hint_start_arrow" to "Inizia 👇"
    )

    val fr = mapOf(
        "app_tagline" to "Apprends les mathématiques via des aventures!",
        "select_avatar" to "Choisis ton Avatar:",
        "enter_name" to "Nom de l'Enfant",
        "enter_name_hint" to "ex. Léo, Léa...",
        "enter_age" to "Âge de l'Enfant",
        "difficulty" to "Difficulté:",
        "diff_easy" to "Facile (Addition/Soustraction 1-10)",
        "diff_medium" to "Moyen (Add/Sou 1-50, Mult)",
        "diff_hard" to "Difficile (Divisions, Nombres jusqu'à 100)",
        "language" to "Choisis la Langue:",
        "btn_create_profile" to "Créer Profil 🚀",
        "btn_add_child" to "Ajouter un Enfant +",
        "no_profiles" to "Bienvenue! Crée un profil pour commencer! 🎉",
        "welcome" to "Bonjour,",
        "play_adventure" to "Démarrer l'Aventure 🏝️",
        "my_stickers" to "Coffre à Jouets 🧸",
        "parents_hub" to "Coin Parents ⚙️",
        "coins" to "Pièces",
        "badges" to "Badges",
        "change_profile" to "Changer de Profil",
        "quest_addition" to "Forêt (Additions)",
        "quest_subtraction" to "Rivière (Soustractions)",
        "quest_multiplication" to "Glace (Multiplications)",
        "quest_division" to "Espace (Divisions)",
        "quest_addition_desc" to "Aide le lapin à ramasser des baies!",
        "quest_subtraction_desc" to "Aide le poisson en éclatant les bulles!",
        "quest_multiplication_desc" to "Aide l'ours à multiplier des blocs!",
        "quest_division_desc" to "Divise des étoiles pour la fusée!",
        "btn_solve" to "Résoudre",
        "quit_adventure" to "Quitter 🚪",
        "question_counter" to "Défi",
        "congrats" to "Hourra! 🎉 Aventure Terminée!",
        "earned_coins" to "Tu as gagné",
        "earned_badge" to "Tu as débloqué un Badge! 🏆",
        "back_home" to "Retour 🏠",
        "correct_answer" to "Génial! Bonne Réponse! ⭐️ (+10 Pièces)",
        "wrong_answer" to "Presque! Essaie encore! ❤️",
        "sticker_shop" to "Boutique",
        "sticker_shop_desc" to "Achète des jouets avec tes pièces!",
        "buy_for" to "Acheter pour",
        "unlocked" to "Débloqué!",
        "insufficient_coins" to "Pas assez de pièces! Joue plus! 🪙",
        "parents_gate_title" to "🔒 SÉCURITÉ PARENTS",
        "parents_gate_desc" to "Vérifiez que vous êtes un parent:",
        "parents_gate_error" to "Oups! Demande à un de tes parents! 😊",
        "btn_submit" to "Vérifier",
        "parent_title" to "Contrôle Parental",
        "parent_subtitle" to "Suivi de progression",
        "accuracy" to "Précision",
        "quests_completed" to "Aventures Résolues",
        "history_logs" to "Historique",
        "delete_profile_warn" to "ATTENTION: Cela supprimera le profil.",
        "btn_delete" to "Supprimer le Profil 🚮",
        "no_logs" to "Pas encore d'exercices terminés.",
        "avatar_bunny" to "Lapin",
        "avatar_fox" to "Renard",
        "avatar_bear" to "Ours",
        "avatar_lion" to "Lion",
        "avatar_owl" to "Hibou",
        "avatar_panda" to "Panda",
        "lbl_active_profile" to "Enfant Actif:",
        "lbl_difficulty" to "Niveau:",
        "lbl_language" to "Langue:",
        "lbl_accuracy_val" to "Précision:",
        "lbl_solved" to "Résolu:",
        "lbl_timestamp" to "DateHeure:",
        "lbl_rewards_tab" to "Mes Badges",
        "lbl_shop_tab" to "Boutique",
        "lbl_toys_box" to "Mes Jouets",
        "range_selector_title" to "Nombres:",
        "range_1_10" to "Apprendre de 1 à 10 🧸",
        "range_10_100" to "Apprendre de 10 à 100 🚀",
        "quest_tracing" to "Traçage ✍️",
        "quest_tracing_desc" to "Trace les lettres le long des flèches!",
        "tracing_title" to "Tracer des Lettres",
        "btn_clear" to "Effacer",
        "btn_undo" to "Annuler",
        "btn_back" to "Retour 🏠",
        "congrats_tracing" to "Hourra! 🎉 Lettre terminée! (+10 Pièces)",
        "btn_next" to "Prochaine ➡️",
        "hint_start_arrow" to "Commence 👇"
    )

    fun get(key: String, lang: String): String {
        return when (lang.lowercase()) {
            "sq" -> sq[key] ?: en[key] ?: key
            "de" -> de[key] ?: en[key] ?: key
            "it" -> it[key] ?: en[key] ?: key
            "fr" -> fr[key] ?: en[key] ?: key
            else -> en[key] ?: key
        }
    }
}
